-- CreateEnum
CREATE TYPE "Position" AS ENUM ('UJONC', 'TAG', 'HR_FELELOS', 'PR_FELELOS', 'TANFOLYAMFELELOS', 'GAZDASAGIS', 'KORVEZETO_HELYETTES', 'KORVEZETO', 'OREGTAG', 'ARCHIVALT');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "position" "Position" NOT NULL DEFAULT 'UJONC';
